<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Regresión lineal</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/yeti.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/jqueryui-1.11.4/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="shortcut icon" href="C:\Users\GalindezR\Desktop\raulgalindez.github.io\favicon-32x32.png" />


<style type="text/css">code{white-space: pre;}</style>
<style type="text/css" data-origin="pandoc">
a.sourceLine { display: inline-block; line-height: 1.25; }
a.sourceLine { pointer-events: none; color: inherit; text-decoration: inherit; }
a.sourceLine:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode { white-space: pre; position: relative; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
code.sourceCode { white-space: pre-wrap; }
a.sourceLine { text-indent: -1em; padding-left: 1em; }
}
pre.numberSource a.sourceLine
  { position: relative; left: -4em; }
pre.numberSource a.sourceLine::before
  { content: attr(title);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; pointer-events: all; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  { background-color: #f8f8f8; }
@media screen {
a.sourceLine::before { text-decoration: underline; }
}
code span.al { color: #ef2929; } /* Alert */
code span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #c4a000; } /* Attribute */
code span.bn { color: #0000cf; } /* BaseN */
code span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4e9a06; } /* Char */
code span.cn { color: #000000; } /* Constant */
code span.co { color: #8f5902; font-style: italic; } /* Comment */
code span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code span.dt { color: #204a87; } /* DataType */
code span.dv { color: #0000cf; } /* DecVal */
code span.er { color: #a40000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #0000cf; } /* Float */
code span.fu { color: #000000; } /* Function */
code span.im { } /* Import */
code span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code span.ot { color: #8f5902; } /* Other */
code span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code span.sc { color: #000000; } /* SpecialChar */
code span.ss { color: #4e9a06; } /* SpecialString */
code span.st { color: #4e9a06; } /* String */
code span.va { color: #000000; } /* Variable */
code span.vs { color: #4e9a06; } /* VerbatimString */
code span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>


<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 45px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h2 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h3 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h4 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h5 {
  padding-top: 50px;
  margin-top: -50px;
}
.section h6 {
  padding-top: 50px;
  margin-top: -50px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row-fluid">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Raúl Galíndez</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="visualizacion.html">
    <span class="fa fa-bar-chart"></span>
     
    Visualización
  </a>
</li>
<li>
  <a href="algoritmos_data_science.html">
    <span class="fa fa-line-chart"></span>
     
    Algoritmos
  </a>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    About
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Regresión lineal</h1>
<h3 class="subtitle">Múltiple y logística</h3>

</div>


<div id="caso-restaurantes-italianos-en-nyc" class="section level1">
<h1><strong><em>Caso: Restaurantes italianos en NYC</em></strong></h1>
<p><img src="img/italian_food_3.jpg" width="425" /></p>
</div>
<div id="introducción" class="section level1">
<h1>Introducción</h1>
<p>Usaremos un dataset que contiene los reviews hechos por <a href="https://www.zagat.com/about-us" target="_blank">Zagat</a> (en 2001) a 168 restauranres italianos en New York.</p>
<p>Cada restaurante recibe una puntuación del 0 al 30 por la calidad de su comida, la decoración y el servicio recibido.<br />
El dataset incluye el valor del precio medio (USD) de un plato (incluye una bebida y la propina).</p>
<p>Responderemos a la interrogante: <em>¿qué factores contribuyen al precio medio de un plato en un restaurante italiano en NYC?</em></p>
<p><strong>Manos a la obra</strong></p>
<p>¿cómo está estructurado el dataset?</p>
<pre><code>FALSE Rows: 168
FALSE Columns: 7
FALSE $ Case       &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1...
FALSE $ Restaurant &lt;chr&gt; &quot;Daniella Ristorante&quot;, &quot;Tello&#39;s Ristorante&quot;, &quot;Biricchino...
FALSE $ Price      &lt;dbl&gt; 43, 32, 34, 41, 54, 52, 34, 34, 39, 44, 45, 47, 52, 35, ...
FALSE $ Food       &lt;dbl&gt; 22, 20, 21, 20, 24, 22, 22, 20, 22, 21, 19, 21, 21, 19, ...
FALSE $ Decor      &lt;int&gt; 18, 19, 13, 20, 19, 22, 16, 18, 19, 17, 17, 19, 19, 17, ...
FALSE $ Service    &lt;int&gt; 20, 19, 18, 17, 21, 21, 21, 21, 22, 19, 20, 21, 20, 19, ...
FALSE $ East       &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...</code></pre>
<p>Tenemos :</p>
<ul>
<li><strong><code>Case</code></strong>: identificador único del restaurante.</li>
<li><strong><code>Restaurante</code></strong>: nombre del restaurante.</li>
<li><strong><code>Price</code></strong>: precio medio de un plato en el restaurante.</li>
<li><strong><code>Food</code></strong>: puntuación recibida por la comida.<br />
</li>
<li><strong><code>Decor</code></strong>: puntuación recibida por la decoración del lugar.<br />
</li>
<li><strong><code>Service</code></strong>`: puntuación recibida por el servicio recibido.<br />
</li>
<li><strong><code>East</code></strong>: variable dicotómica que representa si el restaurante está al este o al oeste de Fifth Avenue.</li>
</ul>
</div>
<div id="análisis-exploratorio-de-datos" class="section level1">
<h1>Análisis Exploratorio de Datos</h1>
<p>En esta etapa buscamos responder a:<br />
- ¿cómo están distribuidas las variables?.<br />
- ¿cómo se relacionan una con la otra?.<br />
- ¿qué patrones representan?.</p>
<p>Un buen approach es usar ´ggpairs()´ function de la librería <code>GGally</code> para explorar visualmente la relación entre las variables y conocer el coeficeinte de correlación lineal de pearson asociados:</p>
<p><img src="regresion_logistica_Restaurantes_italianos_NYC_files/figure-html/EDA-1.png" width="672" /></p>
<ul>
<li>Podemos ver que existe una relación lineal importante entre las variables en cuestión, siendo la que más fuerte está relacionado con el precio <code>Decor</code>, la decoración del lugar.<br />
</li>
<li>Las variables que más se relacionan entre sí, es la puntuación del servicio y la decoración del lugar.<br />
</li>
<li>Para variables dicotómicas<code>east</code>, estos scatter plots no muestran mucha concluyente.</li>
</ul>
<p>Otra forma bastante gráfica de ver la correlación entre las varibles es a través de un correlation heatmaps:</p>
<p><img src="regresion_logistica_Restaurantes_italianos_NYC_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="importancia-de-las-variables-en-el-precio" class="section level1">
<h1>Importancia de las variables en el precio</h1>
<p>Es esperable que la calidad de la comida, o al menos la percepción que se tenga de la misma, esté relacionada con el precio de esta. Chequeemos esto con un modelo de regresión lineal simple (incorporemos un diagrama de dispersión que muestre cómo se relacionan estas variables:</p>
<p><img src="regresion_logistica_Restaurantes_italianos_NYC_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre><code>FALSE 
FALSE Call:
FALSE lm(formula = Price ~ Food, data = nyc)
FALSE 
FALSE Coefficients:
FALSE (Intercept)         Food  
FALSE     -17.832        2.939</code></pre>
<p>Cada punto adicional en la calificación de la calidad de la comida está asociado con un incremento de 2.94 USD en el precio medio de la comida. ¿qué tan grande es este efecto? Esto hay que sopesarlo con el nivel de los precios.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1"><span class="kw">summary</span>(nyc<span class="op">$</span>Price)</a></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    19.0    36.0    43.0    42.7    50.0    65.0</code></pre>
<p>Tomando en cuenta el precio promedio, un cambio adicional de un punto que trae como consecuencia, en promedio, un aumento de 2.94 USD en el precio, no es nada despreciable.</p>
<p>¿hay alguna diferencia en precio entre los restaurantes del lado este y el oeste de la 5ta avenida?</p>
<pre><code>FALSE # A tibble: 2 x 2
FALSE   East  mean_price
FALSE   &lt;fct&gt;      &lt;dbl&gt;
FALSE 1 0           40.4
FALSE 2 1           44.0</code></pre>
<p>En promedio, los precios en el lado este de la 5ta avenida son de 3.58 USD superiores al precio medio en el lado oeste, esto es 8.9% mayor.</p>
<p>¿Lo anterior se da <em>per se</em> por la ubicación misma de los restaurantes o más bien por el hecho de que los restaurantes ubicados al este, tienen mejor comida?</p>
<p>Otra cuestión importante es: ¿cómo varia el precio de los platos respecto a la calidad de la comida y el servicio recibido?</p>
</div>
<div id="parallel-slopes-models" class="section level1">
<h1>Parallel slopes models</h1>
<p>Cuando introducimos una variable cualitativa dicotómica en nuestro modelo, pasamos a estar en presencia de un modelo de pendientes paralelas (parallel slopes model), en este caso la variable <code>east</code>.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb6-1" title="1"><span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>Food <span class="op">+</span><span class="st"> </span><span class="kw">factor</span>(East), <span class="dt">data =</span> nyc)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Price ~ Food + factor(East), data = nyc)
## 
## Coefficients:
##   (Intercept)           Food  factor(East)1  
##       -17.430          2.875          1.459</code></pre>
<p>De la anterior salida tenemos que: - Por cada punto adicional en el review de la calidade la comida, el precio promedio de la comida incrementa en 2.875 USD, despues de controlar el efecto de la locación del restaurante.<br />
- El estar en el lado este de la 5ta avenida agrega 1.46 USD al precio medio de la comida, controlando el efecto de la calidad de la comida.</p>
<p>Visualización del modelo:</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb8-1" title="1"><span class="kw">library</span>(broom)</a>
<a class="sourceLine" id="cb8-2" title="2">mod &lt;-<span class="st"> </span><span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>Food <span class="op">+</span><span class="st"> </span>East, <span class="dt">data =</span> nyc)</a>
<a class="sourceLine" id="cb8-3" title="3"></a>
<a class="sourceLine" id="cb8-4" title="4">augmented_mod &lt;-<span class="st"> </span><span class="kw">augment</span>(mod)</a>
<a class="sourceLine" id="cb8-5" title="5"><span class="kw">glimpse</span>(augmented_mod)</a></code></pre></div>
<pre><code>## Rows: 168
## Columns: 9
## $ Price      &lt;dbl&gt; 43, 32, 34, 41, 54, 52, 34, 34, 39, 44, 45, 47, 52, 35, ...
## $ Food       &lt;dbl&gt; 22, 20, 21, 20, 24, 22, 22, 20, 22, 21, 19, 21, 21, 19, ...
## $ East       &lt;fct&gt; 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...
## $ .fitted    &lt;dbl&gt; 45.81397, 40.06455, 42.93926, 40.06455, 51.56338, 45.813...
## $ .resid     &lt;dbl&gt; -2.8139684, -8.0645539, -8.9392611, 0.9354461, 2.4366172...
## $ .std.resid &lt;dbl&gt; -0.39245231, -1.12158953, -1.24397946, 0.13009852, 0.343...
## $ .hat       &lt;dbl&gt; 0.021640632, 0.016155247, 0.017323431, 0.016155247, 0.03...
## $ .sigma     &lt;dbl&gt; 7.267757, 7.243380, 7.236974, 7.270778, 7.268558, 7.2547...
## $ .cooksd    &lt;dbl&gt; 1.135597e-03, 6.885471e-03, 9.093445e-03, 9.264255e-05, ...</code></pre>
<p><img src="regresion_logistica_Restaurantes_italianos_NYC_files/figure-html/unnamed-chunk-8-1.png" width="672" /></p>
<p>¿qUÉ papel juega el servicio en el precio de los platos? ¿Qué tanto más están dispuestos los clientes a pagar por un mejor servicio, controlando las variables antesiores?</p>
<p>Acá pasamos propiamente a un modelo de regresión múltiple, al incorporar dos variables cuantitativas:</p>
</div>
<div id="fit-model" class="section level1">
<h1>fit model</h1>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb10-1" title="1"> <span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>Food <span class="op">+</span><span class="st"> </span>Service, <span class="dt">data =</span> nyc)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Price ~ Food + Service, data = nyc)
## 
## Coefficients:
## (Intercept)         Food      Service  
##     -21.159        1.495        1.704</code></pre>
<p>Comparado con el primer modelo donde relacionabamos el precio a la calidad de la comida (enumerar los modelos para poder hacer referencia a ellos en el análisis), en el cual por cada punto adicional en lo referente a la calidad d ela comida, el precio aumentaba 2.94 USD, en este modelo donde incorporamos el servicio como modelo explicativo vemos que al controlar el servicio, lo que aumenta el precio de la comida por la calidad de la misma es 1.49 USD, lo cual es menor que cuando considerabamos solo la comidao incluso la comida y la ubicaciónj del restaurante. Esto quiere dcir que la atención recibida es más determinante que la calidad misma, o dicho de otra manera, dos restaurantes con la mismna puntuación en servicio, solo van a aumentear 1.49 USD en el precio medio, por otro lado, luego de controlar el efecto de la calidad de la comidal, el precio medio aumenta 1.7 uSD por cada punto adicional de la calidad del servicio.</p>
<p>A lo anterior pdriamos decir que la calidad del servicio modera el efecto que tiene la calidad de la comida en el precuoi medio, si bien considerando solo la caliudad de la comida el efecto era de casi 3 USD, ya controlantdo por el servivcio recibido, este efecto mengua. De igual manera , la calidad de la comida modera el efecto del servicio (Vease el cofeicnete dfe regresión asociadp o al servicio solo)</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"> <span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>Service, <span class="dt">data =</span> nyc)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Price ~ Service, data = nyc)
## 
## Coefficients:
## (Intercept)      Service  
##     -11.978        2.818</code></pre>
<p>Si bien este ejercicio no tiene en cuenta la multicolinealidad de las variables, en posteriores análisis sería interesnte y necesario analizar la multicolinealidad entre las variables, ya que si bien incorporar variables altasmente correlacionadas no afecta la validez del <span class="math inline">\(R^2\)</span> sí hace que los cofecientes estimados sean inestables (buscar bibliografia e incorporarla). En ocasiones coeficientes que nos lleven a conclusiiones extrañas o poco intuitivas pueden estar relacionadas con la multicolinealidad.</p>
<p>Efecto de la calidad del servicio, de la comida y la ubicación en el precio de la comida</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb14-1" title="1"><span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>Food <span class="op">+</span><span class="st"> </span>Service <span class="op">+</span><span class="st"> </span>East, <span class="dt">data =</span> nyc)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Price ~ Food + Service + East, data = nyc)
## 
## Coefficients:
## (Intercept)         Food      Service        East1  
##    -20.8155       1.4863       1.6647       0.9649</code></pre>
<p>Comparando el efecto que tiene el hecho de que el restauranre se encuentre en el lado Este de la 5ta avenida (controlando por la calidad de la comida y del servicio), este es menor que el impacto que tienen las otras dos variables. Es decir, tomando en cuenta estas 3 variabels, es más importante el efecto de la calidad de la comida y del servicio que la ubicación.</p>
<p>Los coeficientes asociadasas a la comida y el sertbicvio no tyuvierron cambios imporrantes con respecto a los modelos anteriores.</p>
<p>Incorporemos las 4 variables a ver qué talco</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb16-1" title="1"><span class="kw">lm</span>(Price <span class="op">~</span><span class="st"> </span>Food <span class="op">+</span><span class="st"> </span>Service <span class="op">+</span><span class="st"> </span>Decor <span class="op">+</span><span class="st"> </span>East, <span class="dt">data=</span> nyc)</a></code></pre></div>
<pre><code>## 
## Call:
## lm(formula = Price ~ Food + Service + Decor + East, data = nyc)
## 
## Coefficients:
## (Intercept)         Food      Service        Decor        East1  
##  -24.023800     1.538120    -0.002727     1.910087     2.068050</code></pre>
<p>¿qué podemos decir de los coeficienters anteriores? - El cambio que suffiró el coeficiente asociado a <code>Service</code> puiede estar asociado a la multicolienadlidad (ercordemos que habiamos visto que habia una alta relacion entre la caliudad de la comida, la decoracion y y el servicio).</p>
<ul>
<li>Una vez que controlamos la calidad de los alimentos, la decoración y la ubicación, la información adicional transmitida por el servicio es insignificante.</li>
</ul>
<p>Ester ejercicio no abarca la inferencia acerca de los parametros,. queda como proximo ejercicio.</p>
<p>Visualicemos Un buen paso a paso para un análisis de regresión multiple es: - Analizar la asociación entre las variables de insumo –&gt; diagrama de dispersín y correlación bivariada.<br />
- validar el modelo –&gt; Tabla ANOVA<br />
- ¿qué tanto explica el modelo? –&gt; coeficiente de determinación ajustado <span class="math inline">\(R^2\)</span><br />
- Determinar los coeficientes de nuestro modelo y qué tanto aportan a la explicación de la variable en estudio.<br />
- Predecir los valores de nuestra variable usando el modelo ajustado.</p>
</div>

<p>Copyright &copy; 2020 Raúl Galíndez, Inc. All rights reserved.</p>


</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
