<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Regresión lineal</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/paper.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/textmate.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-5.1.0/css/all.css" rel="stylesheet" />
<link href="site_libs/font-awesome-5.1.0/css/v4-shims.css" rel="stylesheet" />
<link rel="shortcut icon" href="C:\Users\GalindezR\Desktop\raulgalindez.github.io\favicon-32x32.png" />

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>

<link rel="stylesheet" href="styles.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 64px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h2 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h3 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h4 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h5 {
  padding-top: 69px;
  margin-top: -69px;
}
.section h6 {
  padding-top: 69px;
  margin-top: -69px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">My Website</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li>
  <a href="graficando.html">
    <span class="fa fa-bar-chart"></span>
     
    Graficando
  </a>
</li>
<li>
  <a href="regresion_muliple_logit.html">
    <span class="fa fa-line-chart"></span>
     
    RLM + Logit
  </a>
</li>
<li>
  <a href="about.html">
    <span class="fa fa-info"></span>
     
    About
  </a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Regresión lineal</h1>
<h3 class="subtitle">Múltiple y logística</h3>

</div>


<p><strong><em>Caso: Restaurantes italianos en NYC</em></strong></p>
<p><img src="img/italian_food_3.jpg" /><!-- --></p>
<p>Usaremos un dataset que contiene los reviews hechos por <a href="https://www.zagat.com/about-us" target="_blank">Zagat</a> (en 2001) a 168 restauranres italianos en New York.</p>
<p>Cada restaurante recibe una puntuación del 0 al 30 por la calidad de su comida, la decoración y el servicio recibido.<br />
El dataset incluye el valor del precio medio (USD) de un plato (incluye una bebida y la propina)</p>
<p>Responderemos a la interrogante: <em>¿qué factores contribuyen al precio medio de un plato en un restaurante italiano en NYC?</em></p>
<p><strong>Manos a la obra</strong></p>
<p>¿cómo está estructurado el dataset?</p>
<pre class="r"><code>glimpse(nyc)</code></pre>
<pre><code>## Rows: 168
## Columns: 7
## $ Case       &lt;int&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 1...
## $ Restaurant &lt;chr&gt; &quot;Daniella Ristorante&quot;, &quot;Tello&#39;s Ristorante&quot;, &quot;Biricchino...
## $ Price      &lt;int&gt; 43, 32, 34, 41, 54, 52, 34, 34, 39, 44, 45, 47, 52, 35, ...
## $ Food       &lt;int&gt; 22, 20, 21, 20, 24, 22, 22, 20, 22, 21, 19, 21, 21, 19, ...
## $ Decor      &lt;int&gt; 18, 19, 13, 20, 19, 22, 16, 18, 19, 17, 17, 19, 19, 17, ...
## $ Service    &lt;int&gt; 20, 19, 18, 17, 21, 21, 21, 21, 22, 19, 20, 21, 20, 19, ...
## $ East       &lt;int&gt; 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,...</code></pre>
<p>Tenemos :</p>
<ul>
<li><strong><code>Case</code></strong>:</li>
<li><code>Restaurante</code>: nombre del restaurante.</li>
<li><code>Price</code>: precio medio de un plato en el restaurante.</li>
<li><code>Food</code>: puntuación recibida por la comida.<br />
</li>
<li><code>Decor</code>: puntuación recibida por la decoración del lugar.<br />
</li>
<li><code>Service</code>: puntuación recibida por el servicio recibido.<br />
</li>
<li><code>East</code>: variable dicotómica que representa si el restaurante está al este o al oeste de Fifth Avenue.</li>
</ul>
<div id="análisis-exploratorio-de-datos" class="section level1">
<h1>Análisis Exploratorio de Datos</h1>
<p>¿cómo están distribuidas las variables? ¿cómo se relacionan una con la otra? ¿qué patrones representan?</p>
<p>Un buen aprach es usar ´pairs()´ funtion para explorar visualmente la relación entre las variables:</p>
<pre><code>FALSE Registered S3 method overwritten by &#39;GGally&#39;:
FALSE   method from   
FALSE   +.gg   ggplot2</code></pre>
<p><img src="regresion_muliple_logit_files/figure-html/eda-1.png" width="672" /></p>
<ul>
<li>Podemos ver que la variable que más se relaciona, linealmente, con el precio medio es la puntuación obtenida por la decoración del lugar.</li>
<li>Las variables que más se relacionan entre sí, es la puntruación de la decoración y del servicio.<br />
</li>
<li>Para variables dicotómicas<code>east</code>, estos scatter plots no muestran mucha concluyente.</li>
</ul>
<p>¿hay alguna diferencia en precio entre los restaurantes del lado este y el oeste de la 5ta avenida?</p>
<pre><code>FALSE `summarise()` ungrouping output (override with `.groups` argument)</code></pre>
<pre><code>FALSE # A tibble: 2 x 2
FALSE    East mean_price
FALSE   &lt;int&gt;      &lt;dbl&gt;
FALSE 1     0       40.4
FALSE 2     1       44.0</code></pre>
<p>En promedio, los precios en el lado este de la 5ta avenida son de 3.58 USD superiores al precio medio en el lado oeste, esto es 0.09% mayor.</p>
<p>¿Lo anterior se da <em>per se</em> por la ubicación misma de los restaurantes o más bien por el hecho de que los restaurantes ubicados al este, tienen mejor comida?</p>
<p>Otra cuestión importante es: ¿cómo varia el precio de los platos respecto a la calidad de la comida y el servicio recibido?</p>
<pre class="r"><code>lm(Price ~ Food + East, data = nyc)</code></pre>
<pre><code>## 
## Call:
## lm(formula = Price ~ Food + East, data = nyc)
## 
## Coefficients:
## (Intercept)         Food         East  
##     -17.430        2.875        1.459</code></pre>
<p>Cuando introducimos una variable cualitativa dicotómica en nuestro modelo, pasamos a estar en presencia de un modelo de pendientes paralelas (parallel slopes model), en este caso la variable</p>
<p>De la anterior salida tenemos que: - Por cada punto adicional en el review de la calidade la comida, el precio promedio de la comida incrementa en 2.875 USD, despues de controlar el efecto de la locación del restaurante. - El estar en el lado este de la 5ta avenida agrega 1.46 USD al precio medio de la comida, controlando el efecto de la calidad de la comida.</p>
<p>Pendiente: buscar una visualización para un gráfico con dos vairables explciativas numericas (sería el plano , pero en DataCamp no dice como se hace)</p>
<p>Un buen paso a paso para un análisis de regresión multiple es: - Analizar la asociación entre las variables de insumo –&gt; diagrama de dispersín y correlación bivariada. - validar el modelo –&gt; Tabla ANOVA - ¿qué tanto explica el modelo? –&gt; coeficiente de determinación ajustado <span class="math inline">\(R^2\)</span> - Determinar los coeficientes de nuestro modelo y qué tanto aportan a la explicación de la variable en estudio. - Predecir los valores de nuestra variable usando el modelo ajustado.</p>
</div>

<p>Copyright &copy; 2020 Raúl Galíndez, Inc. All rights reserved.</p>



</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
